//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace TesteWCF.smartparking {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServico", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Image))]
    public partial class Servico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarVagasDisponiveisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservarVagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaSituacaoVagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LocalizarCarroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servico() {
            this.Url = global::TesteWCF.Properties.Settings.Default.TesteWCF_smartparking_Servico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event ListarVagasDisponiveisCompletedEventHandler ListarVagasDisponiveisCompleted;
        
        /// <remarks/>
        public event ReservarVagaCompletedEventHandler ReservarVagaCompleted;
        
        /// <remarks/>
        public event ConsultaSituacaoVagaCompletedEventHandler ConsultaSituacaoVagaCompleted;
        
        /// <remarks/>
        public event LocalizarCarroCompletedEventHandler LocalizarCarroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/ListarVagasDisponiveis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
        public dtoVaga[] ListarVagasDisponiveis() {
            object[] results = this.Invoke("ListarVagasDisponiveis", new object[0]);
            return ((dtoVaga[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarVagasDisponiveisAsync() {
            this.ListarVagasDisponiveisAsync(null);
        }
        
        /// <remarks/>
        public void ListarVagasDisponiveisAsync(object userState) {
            if ((this.ListarVagasDisponiveisOperationCompleted == null)) {
                this.ListarVagasDisponiveisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarVagasDisponiveisOperationCompleted);
            }
            this.InvokeAsync("ListarVagasDisponiveis", new object[0], this.ListarVagasDisponiveisOperationCompleted, userState);
        }
        
        private void OnListarVagasDisponiveisOperationCompleted(object arg) {
            if ((this.ListarVagasDisponiveisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarVagasDisponiveisCompleted(this, new ListarVagasDisponiveisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/ReservarVaga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReservarVaga(int Id_Vaga, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_VagaSpecified, int Id_Carro, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_CarroSpecified, out bool ReservarVagaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ReservarVagaResultSpecified) {
            object[] results = this.Invoke("ReservarVaga", new object[] {
                        Id_Vaga,
                        Id_VagaSpecified,
                        Id_Carro,
                        Id_CarroSpecified});
            ReservarVagaResult = ((bool)(results[0]));
            ReservarVagaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ReservarVagaAsync(int Id_Vaga, bool Id_VagaSpecified, int Id_Carro, bool Id_CarroSpecified) {
            this.ReservarVagaAsync(Id_Vaga, Id_VagaSpecified, Id_Carro, Id_CarroSpecified, null);
        }
        
        /// <remarks/>
        public void ReservarVagaAsync(int Id_Vaga, bool Id_VagaSpecified, int Id_Carro, bool Id_CarroSpecified, object userState) {
            if ((this.ReservarVagaOperationCompleted == null)) {
                this.ReservarVagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservarVagaOperationCompleted);
            }
            this.InvokeAsync("ReservarVaga", new object[] {
                        Id_Vaga,
                        Id_VagaSpecified,
                        Id_Carro,
                        Id_CarroSpecified}, this.ReservarVagaOperationCompleted, userState);
        }
        
        private void OnReservarVagaOperationCompleted(object arg) {
            if ((this.ReservarVagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservarVagaCompleted(this, new ReservarVagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/ConsultaSituacaoVaga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public dtoSituacaoVaga ConsultaSituacaoVaga(int Id_Vaga, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_VagaSpecified) {
            object[] results = this.Invoke("ConsultaSituacaoVaga", new object[] {
                        Id_Vaga,
                        Id_VagaSpecified});
            return ((dtoSituacaoVaga)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSituacaoVagaAsync(int Id_Vaga, bool Id_VagaSpecified) {
            this.ConsultaSituacaoVagaAsync(Id_Vaga, Id_VagaSpecified, null);
        }
        
        /// <remarks/>
        public void ConsultaSituacaoVagaAsync(int Id_Vaga, bool Id_VagaSpecified, object userState) {
            if ((this.ConsultaSituacaoVagaOperationCompleted == null)) {
                this.ConsultaSituacaoVagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSituacaoVagaOperationCompleted);
            }
            this.InvokeAsync("ConsultaSituacaoVaga", new object[] {
                        Id_Vaga,
                        Id_VagaSpecified}, this.ConsultaSituacaoVagaOperationCompleted, userState);
        }
        
        private void OnConsultaSituacaoVagaOperationCompleted(object arg) {
            if ((this.ConsultaSituacaoVagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSituacaoVagaCompleted(this, new ConsultaSituacaoVagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/LocalizarCarro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public dtoCaminho LocalizarCarro(int Id_QRCode, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_QRCodeSpecified, int Id_Carro, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_CarroSpecified) {
            object[] results = this.Invoke("LocalizarCarro", new object[] {
                        Id_QRCode,
                        Id_QRCodeSpecified,
                        Id_Carro,
                        Id_CarroSpecified});
            return ((dtoCaminho)(results[0]));
        }
        
        /// <remarks/>
        public void LocalizarCarroAsync(int Id_QRCode, bool Id_QRCodeSpecified, int Id_Carro, bool Id_CarroSpecified) {
            this.LocalizarCarroAsync(Id_QRCode, Id_QRCodeSpecified, Id_Carro, Id_CarroSpecified, null);
        }
        
        /// <remarks/>
        public void LocalizarCarroAsync(int Id_QRCode, bool Id_QRCodeSpecified, int Id_Carro, bool Id_CarroSpecified, object userState) {
            if ((this.LocalizarCarroOperationCompleted == null)) {
                this.LocalizarCarroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocalizarCarroOperationCompleted);
            }
            this.InvokeAsync("LocalizarCarro", new object[] {
                        Id_QRCode,
                        Id_QRCodeSpecified,
                        Id_Carro,
                        Id_CarroSpecified}, this.LocalizarCarroOperationCompleted, userState);
        }
        
        private void OnLocalizarCarroOperationCompleted(object arg) {
            if ((this.LocalizarCarroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LocalizarCarroCompleted(this, new LocalizarCarroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bitmap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial class Image {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial class Bitmap : Image {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class dtoCaminho {
        
        private Bitmap[] listaImagensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
        public Bitmap[] ListaImagens {
            get {
                return this.listaImagensField;
            }
            set {
                this.listaImagensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class dtoSituacaoVaga {
        
        private bool vagaOcupadaField;
        
        private bool vagaOcupadaFieldSpecified;
        
        private bool vagaPerdidaField;
        
        private bool vagaPerdidaFieldSpecified;
        
        /// <remarks/>
        public bool VagaOcupada {
            get {
                return this.vagaOcupadaField;
            }
            set {
                this.vagaOcupadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VagaOcupadaSpecified {
            get {
                return this.vagaOcupadaFieldSpecified;
            }
            set {
                this.vagaOcupadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool VagaPerdida {
            get {
                return this.vagaPerdidaField;
            }
            set {
                this.vagaPerdidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VagaPerdidaSpecified {
            get {
                return this.vagaPerdidaFieldSpecified;
            }
            set {
                this.vagaPerdidaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class dtoVaga {
        
        private string andarField;
        
        private string blocoField;
        
        private int id_VagaField;
        
        private bool id_VagaFieldSpecified;
        
        private string vagaField;
        
        private bool disponibilidadeField;
        
        private bool disponibilidadeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Andar {
            get {
                return this.andarField;
            }
            set {
                this.andarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bloco {
            get {
                return this.blocoField;
            }
            set {
                this.blocoField = value;
            }
        }
        
        /// <remarks/>
        public int Id_Vaga {
            get {
                return this.id_VagaField;
            }
            set {
                this.id_VagaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_VagaSpecified {
            get {
                return this.id_VagaFieldSpecified;
            }
            set {
                this.id_VagaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Vaga {
            get {
                return this.vagaField;
            }
            set {
                this.vagaField = value;
            }
        }
        
        /// <remarks/>
        public bool disponibilidade {
            get {
                return this.disponibilidadeField;
            }
            set {
                this.disponibilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disponibilidadeSpecified {
            get {
                return this.disponibilidadeFieldSpecified;
            }
            set {
                this.disponibilidadeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ListarVagasDisponiveisCompletedEventHandler(object sender, ListarVagasDisponiveisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarVagasDisponiveisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarVagasDisponiveisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtoVaga[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtoVaga[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ReservarVagaCompletedEventHandler(object sender, ReservarVagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservarVagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservarVagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ReservarVagaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ReservarVagaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaSituacaoVagaCompletedEventHandler(object sender, ConsultaSituacaoVagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSituacaoVagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSituacaoVagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtoSituacaoVaga Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtoSituacaoVaga)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LocalizarCarroCompletedEventHandler(object sender, LocalizarCarroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LocalizarCarroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LocalizarCarroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtoCaminho Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtoCaminho)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591