//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace TesteWCF.smartparking {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServico", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Image))]
    public partial class Servico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarAndaresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBlocosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarVagasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservarVagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaSituacaoVagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LocalizarCarroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servico() {
            this.Url = global::TesteWCF.Properties.Settings.Default.TesteWCF_smartparking_Servico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarAndaresCompletedEventHandler ListarAndaresCompleted;
        
        /// <remarks/>
        public event ListarBlocosCompletedEventHandler ListarBlocosCompleted;
        
        /// <remarks/>
        public event ListarVagasCompletedEventHandler ListarVagasCompleted;
        
        /// <remarks/>
        public event ReservarVagaCompletedEventHandler ReservarVagaCompleted;
        
        /// <remarks/>
        public event ConsultaSituacaoVagaCompletedEventHandler ConsultaSituacaoVagaCompleted;
        
        /// <remarks/>
        public event LocalizarCarroCompletedEventHandler LocalizarCarroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/ListarAndares", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
        public dtoAndar[] ListarAndares() {
            object[] results = this.Invoke("ListarAndares", new object[0]);
            return ((dtoAndar[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAndaresAsync() {
            this.ListarAndaresAsync(null);
        }
        
        /// <remarks/>
        public void ListarAndaresAsync(object userState) {
            if ((this.ListarAndaresOperationCompleted == null)) {
                this.ListarAndaresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAndaresOperationCompleted);
            }
            this.InvokeAsync("ListarAndares", new object[0], this.ListarAndaresOperationCompleted, userState);
        }
        
        private void OnListarAndaresOperationCompleted(object arg) {
            if ((this.ListarAndaresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAndaresCompleted(this, new ListarAndaresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/ListarBlocos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
        public dtoBloco[] ListarBlocos(int Id_Andar, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_AndarSpecified) {
            object[] results = this.Invoke("ListarBlocos", new object[] {
                        Id_Andar,
                        Id_AndarSpecified});
            return ((dtoBloco[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarBlocosAsync(int Id_Andar, bool Id_AndarSpecified) {
            this.ListarBlocosAsync(Id_Andar, Id_AndarSpecified, null);
        }
        
        /// <remarks/>
        public void ListarBlocosAsync(int Id_Andar, bool Id_AndarSpecified, object userState) {
            if ((this.ListarBlocosOperationCompleted == null)) {
                this.ListarBlocosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBlocosOperationCompleted);
            }
            this.InvokeAsync("ListarBlocos", new object[] {
                        Id_Andar,
                        Id_AndarSpecified}, this.ListarBlocosOperationCompleted, userState);
        }
        
        private void OnListarBlocosOperationCompleted(object arg) {
            if ((this.ListarBlocosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBlocosCompleted(this, new ListarBlocosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/ListarVagas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
        public dtoVaga[] ListarVagas(int Id_Bloco, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_BlocoSpecified) {
            object[] results = this.Invoke("ListarVagas", new object[] {
                        Id_Bloco,
                        Id_BlocoSpecified});
            return ((dtoVaga[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarVagasAsync(int Id_Bloco, bool Id_BlocoSpecified) {
            this.ListarVagasAsync(Id_Bloco, Id_BlocoSpecified, null);
        }
        
        /// <remarks/>
        public void ListarVagasAsync(int Id_Bloco, bool Id_BlocoSpecified, object userState) {
            if ((this.ListarVagasOperationCompleted == null)) {
                this.ListarVagasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarVagasOperationCompleted);
            }
            this.InvokeAsync("ListarVagas", new object[] {
                        Id_Bloco,
                        Id_BlocoSpecified}, this.ListarVagasOperationCompleted, userState);
        }
        
        private void OnListarVagasOperationCompleted(object arg) {
            if ((this.ListarVagasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarVagasCompleted(this, new ListarVagasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/ReservarVaga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReservarVaga(int Id_Vaga, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_VagaSpecified, int Id_Carro, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_CarroSpecified, out bool ReservarVagaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ReservarVagaResultSpecified) {
            object[] results = this.Invoke("ReservarVaga", new object[] {
                        Id_Vaga,
                        Id_VagaSpecified,
                        Id_Carro,
                        Id_CarroSpecified});
            ReservarVagaResult = ((bool)(results[0]));
            ReservarVagaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ReservarVagaAsync(int Id_Vaga, bool Id_VagaSpecified, int Id_Carro, bool Id_CarroSpecified) {
            this.ReservarVagaAsync(Id_Vaga, Id_VagaSpecified, Id_Carro, Id_CarroSpecified, null);
        }
        
        /// <remarks/>
        public void ReservarVagaAsync(int Id_Vaga, bool Id_VagaSpecified, int Id_Carro, bool Id_CarroSpecified, object userState) {
            if ((this.ReservarVagaOperationCompleted == null)) {
                this.ReservarVagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservarVagaOperationCompleted);
            }
            this.InvokeAsync("ReservarVaga", new object[] {
                        Id_Vaga,
                        Id_VagaSpecified,
                        Id_Carro,
                        Id_CarroSpecified}, this.ReservarVagaOperationCompleted, userState);
        }
        
        private void OnReservarVagaOperationCompleted(object arg) {
            if ((this.ReservarVagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservarVagaCompleted(this, new ReservarVagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/ConsultaSituacaoVaga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public dtoSituacaoVaga ConsultaSituacaoVaga(int Id_Vaga, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_VagaSpecified) {
            object[] results = this.Invoke("ConsultaSituacaoVaga", new object[] {
                        Id_Vaga,
                        Id_VagaSpecified});
            return ((dtoSituacaoVaga)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSituacaoVagaAsync(int Id_Vaga, bool Id_VagaSpecified) {
            this.ConsultaSituacaoVagaAsync(Id_Vaga, Id_VagaSpecified, null);
        }
        
        /// <remarks/>
        public void ConsultaSituacaoVagaAsync(int Id_Vaga, bool Id_VagaSpecified, object userState) {
            if ((this.ConsultaSituacaoVagaOperationCompleted == null)) {
                this.ConsultaSituacaoVagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSituacaoVagaOperationCompleted);
            }
            this.InvokeAsync("ConsultaSituacaoVaga", new object[] {
                        Id_Vaga,
                        Id_VagaSpecified}, this.ConsultaSituacaoVagaOperationCompleted, userState);
        }
        
        private void OnConsultaSituacaoVagaOperationCompleted(object arg) {
            if ((this.ConsultaSituacaoVagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSituacaoVagaCompleted(this, new ConsultaSituacaoVagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServico/LocalizarCarro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public dtoCaminho LocalizarCarro(int Id_QRCode, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_QRCodeSpecified, int Id_Carro, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_CarroSpecified) {
            object[] results = this.Invoke("LocalizarCarro", new object[] {
                        Id_QRCode,
                        Id_QRCodeSpecified,
                        Id_Carro,
                        Id_CarroSpecified});
            return ((dtoCaminho)(results[0]));
        }
        
        /// <remarks/>
        public void LocalizarCarroAsync(int Id_QRCode, bool Id_QRCodeSpecified, int Id_Carro, bool Id_CarroSpecified) {
            this.LocalizarCarroAsync(Id_QRCode, Id_QRCodeSpecified, Id_Carro, Id_CarroSpecified, null);
        }
        
        /// <remarks/>
        public void LocalizarCarroAsync(int Id_QRCode, bool Id_QRCodeSpecified, int Id_Carro, bool Id_CarroSpecified, object userState) {
            if ((this.LocalizarCarroOperationCompleted == null)) {
                this.LocalizarCarroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocalizarCarroOperationCompleted);
            }
            this.InvokeAsync("LocalizarCarro", new object[] {
                        Id_QRCode,
                        Id_QRCodeSpecified,
                        Id_Carro,
                        Id_CarroSpecified}, this.LocalizarCarroOperationCompleted, userState);
        }
        
        private void OnLocalizarCarroOperationCompleted(object arg) {
            if ((this.LocalizarCarroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LocalizarCarroCompleted(this, new LocalizarCarroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class dtoAndar {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nomeField;
        
        private int qtdLiveField;
        
        private bool qtdLiveFieldSpecified;
        
        private int qtdVagasField;
        
        private bool qtdVagasFieldSpecified;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public int QtdLive {
            get {
                return this.qtdLiveField;
            }
            set {
                this.qtdLiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtdLiveSpecified {
            get {
                return this.qtdLiveFieldSpecified;
            }
            set {
                this.qtdLiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int QtdVagas {
            get {
                return this.qtdVagasField;
            }
            set {
                this.qtdVagasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtdVagasSpecified {
            get {
                return this.qtdVagasFieldSpecified;
            }
            set {
                this.qtdVagasFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bitmap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial class Image {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial class Bitmap : Image {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class dtoCaminho {
        
        private Bitmap[] listaImagensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
        public Bitmap[] ListaImagens {
            get {
                return this.listaImagensField;
            }
            set {
                this.listaImagensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class dtoSituacaoVaga {
        
        private bool vagaOcupadaField;
        
        private bool vagaOcupadaFieldSpecified;
        
        private bool vagaPerdidaField;
        
        private bool vagaPerdidaFieldSpecified;
        
        /// <remarks/>
        public bool VagaOcupada {
            get {
                return this.vagaOcupadaField;
            }
            set {
                this.vagaOcupadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VagaOcupadaSpecified {
            get {
                return this.vagaOcupadaFieldSpecified;
            }
            set {
                this.vagaOcupadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool VagaPerdida {
            get {
                return this.vagaPerdidaField;
            }
            set {
                this.vagaPerdidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VagaPerdidaSpecified {
            get {
                return this.vagaPerdidaFieldSpecified;
            }
            set {
                this.vagaPerdidaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class dtoVaga {
        
        private bool disponivelField;
        
        private bool disponivelFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nomeField;
        
        /// <remarks/>
        public bool Disponivel {
            get {
                return this.disponivelField;
            }
            set {
                this.disponivelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisponivelSpecified {
            get {
                return this.disponivelFieldSpecified;
            }
            set {
                this.disponivelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ParkingService")]
    public partial class dtoBloco {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nomeField;
        
        private int qtdLiveField;
        
        private bool qtdLiveFieldSpecified;
        
        private int qtdVagasField;
        
        private bool qtdVagasFieldSpecified;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public int QtdLive {
            get {
                return this.qtdLiveField;
            }
            set {
                this.qtdLiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtdLiveSpecified {
            get {
                return this.qtdLiveFieldSpecified;
            }
            set {
                this.qtdLiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int QtdVagas {
            get {
                return this.qtdVagasField;
            }
            set {
                this.qtdVagasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtdVagasSpecified {
            get {
                return this.qtdVagasFieldSpecified;
            }
            set {
                this.qtdVagasFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ListarAndaresCompletedEventHandler(object sender, ListarAndaresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAndaresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAndaresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtoAndar[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtoAndar[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ListarBlocosCompletedEventHandler(object sender, ListarBlocosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBlocosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBlocosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtoBloco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtoBloco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ListarVagasCompletedEventHandler(object sender, ListarVagasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarVagasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarVagasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtoVaga[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtoVaga[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ReservarVagaCompletedEventHandler(object sender, ReservarVagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservarVagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservarVagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ReservarVagaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ReservarVagaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaSituacaoVagaCompletedEventHandler(object sender, ConsultaSituacaoVagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSituacaoVagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSituacaoVagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtoSituacaoVaga Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtoSituacaoVaga)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LocalizarCarroCompletedEventHandler(object sender, LocalizarCarroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LocalizarCarroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LocalizarCarroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtoCaminho Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtoCaminho)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591