//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caminho_Mapa
    {
        public int Id { get; set; }
        public int Id_Caminho { get; set; }
        public int Id_Mapa { get; set; }
    
        public virtual Caminho Caminho { get; set; }
        public virtual Mapa Mapa { get; set; }
    }
}
