//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public Carro()
        {
            this.Vaga = new HashSet<Vaga>();
        }
    
        public int Id { get; set; }
        public int Id_Cliente { get; set; }
        public string Marca { get; set; }
        public string Placa { get; set; }
        public int Id_Tag { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Vaga> Vaga { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
