//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoQR
    {
        public CodigoQR()
        {
            this.Totem = new HashSet<Totem>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Valor { get; set; }
    
        public virtual ICollection<Totem> Totem { get; set; }
    }
}
