//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapa
    {
        public Mapa()
        {
            this.Caminho_Mapa = new HashSet<Caminho_Mapa>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public byte[] Imagem { get; set; }
    
        public virtual ICollection<Caminho_Mapa> Caminho_Mapa { get; set; }
    }
}
