//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingDBEntities : DbContext
    {
        public ParkingDBEntities()
            : base("name=ParkingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Andar> Andar { get; set; }
        public DbSet<Bloco> Bloco { get; set; }
        public DbSet<Caminho> Caminho { get; set; }
        public DbSet<Caminho_Mapa> Caminho_Mapa { get; set; }
        public DbSet<Carro> Carro { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Mapa> Mapa { get; set; }
        public DbSet<Totem> Totem { get; set; }
        public DbSet<Vaga> Vaga { get; set; }
        public DbSet<Tag> Tag { get; set; }
    }
}
