//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Carro = new HashSet<Carro>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
    
        public virtual ICollection<Carro> Carro { get; set; }
    }
}
