//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totem
    {
        public Totem()
        {
            this.Mapa_Vaga = new HashSet<Mapa_Vaga>();
        }
    
        public int Id { get; set; }
        public int Id_Andar { get; set; }
        public int Id_CodigoQR { get; set; }
        public string Nome { get; set; }
    
        public virtual Andar Andar { get; set; }
        public virtual CodigoQR CodigoQR { get; set; }
        public virtual ICollection<Mapa_Vaga> Mapa_Vaga { get; set; }
    }
}
