//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaga
    {
        public Vaga()
        {
            this.Mapa_Vaga = new HashSet<Mapa_Vaga>();
        }
    
        public int Id { get; set; }
        public int Id_Bloco { get; set; }
        public string Nome { get; set; }
        public string Situacao { get; set; }
        public Nullable<int> Id_Carro { get; set; }
        public Nullable<System.DateTime> HoraReserva { get; set; }
    
        public virtual Bloco Bloco { get; set; }
        public virtual ICollection<Mapa_Vaga> Mapa_Vaga { get; set; }
        public virtual Carro Carro { get; set; }
    }
}
